on:
    push:
        branches:
            - develop
name: build gatsby
jobs:
    build_gatsby:
        name: build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
              token: ${{ secrets.API_KEY }}
              submodules: true

        - uses: enriikke/gatsby-gh-pages-action@v2
          with:
              access-token: ${{ secrets.API_KEY }}
              deploy-branch: gh-pages
              skip-publish: false